dfs:
  url: 94.191.83.120:8181
# 114.115.171.119 root Mall123!#$
druid-master:
  jdbcUrl: jdbc:mysql://119.3.30.5:3307/mask?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
  username: root
  password: root
  driver-class-name: com.mysql.jdbc.Driver
  minIdle: 2
  maxActive: 10
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 1 FROM DUAL
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20
  filters: stat,wall
  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
druid-slave:
  jdbcUrl: jdbc:mysql://119.3.30.5:3308/mask?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
  username: root
  password: root
  driver-class-name: com.mysql.jdbc.Driver
  minIdle: 2
  maxActive: 10
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 1 FROM DUAL
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20
  filters: stat,wall
  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

mybatis:
  mapper-locations: classpath*:mapping/**/*.xml
  config-location: classpath:SqlMapConfig.xml

spring:
  sleuth:
    sampler:
      percentage: 1.0
    web:
      client:
        enabled: true
  zipkin:
    base-url: http://106.55.152.41:9411/
    sender:
      type: kafka
  cloud:
    stream:
      kafka:
        binder:
          brokers: 47.102.147.24:9092
    alibaba:
      seata:
        tx-service-group: pay_tx_group
  kafka:
    bootstrap-servers: 47.102.147.24:9092
  redis:
    host: 119.3.30.5
    port: 6379
    password: 1659868245
    jedis:
      pool:
        max-active: 100
        max-idle: 100
        max-wait: -1
        min-idle: 0
  data:
    mongodb:
      uri: mongodb://119.3.30.5:27017/mask
  datasource:
    initialize: false
  application:
    name: mask-product-service
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8763/eureka/
    register-with-eureka: true
    fetch-registry: true
  #instance:
    #hostname:
    #ip-address: 119.45.45.184
    #prefer-ip-address: true
    #instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 5000
  OkToRetryOnAllOperations: false
  MaxAutoRetriesNextServer: 0
  MaxAutoRetries: 0

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: info
    cn:
      hezhiling:
        mask:
          dao: debug
    org:
      springframework:
        cloud:
          sleuth: debug